import { CSXIndexData, CSXStock, NewsItem, CSXDisclosure, MarketAlert } from '../types/csx';
import { computeTechnicalIndicators } from './technicalAnalysis';
import { generate7DayForecast } from './forecastingEngine';

// Helper to generate realistic historical price points respecting CSX tick sizes
function generateHistory(basePrice: number, volatility = 0.015, days = 180, trend = 0.0003, tickSize = 20) {
  const points = [];
  let price = Math.round((basePrice * (1 - days * trend * 0.8)) / tickSize) * tickSize;
  const now = new Date();
  
  for (let i = days; i >= 0; i--) {
    const d = new Date(now);
    d.setDate(d.getDate() - i);
    // skip weekends
    if (d.getDay() === 0 || d.getDay() === 6) continue;

    const noise = (Math.random() - 0.48) * volatility;
    price = Math.max(tickSize * 10, Math.round((price * (1 + trend + noise)) / tickSize) * tickSize);
    const daySpread = Math.max(tickSize, Math.round((price * volatility * 0.7) / tickSize) * tickSize);
    const high = price + Math.round((Math.random() * daySpread) / tickSize) * tickSize;
    const low = Math.max(tickSize * 5, price - Math.round((Math.random() * daySpread) / tickSize) * tickSize);
    const open = Math.round(((low + high) / 2) / tickSize) * tickSize;
    const volume = Math.round(5000 + Math.random() * 45000 + (Math.random() > 0.85 ? 80000 : 0));

    points.push({
      date: d.toISOString().split('T')[0],
      open,
      high,
      low,
      close: price,
      volume,
      valueKHR: price * volume,
    });
  }

  // Ensure last close matches current target price exactly
  if (points.length > 0) {
    points[points.length - 1].close = basePrice;
    points[points.length - 1].high = Math.max(points[points.length - 1].high, basePrice);
    points[points.length - 1].low = Math.min(points[points.length - 1].low, basePrice);
  }

  return points;
}

export const CSX_INDEX_DATA: CSXIndexData = {
  index: 650.99,
  change: 2.45,
  changePercent: 0.38,
  previousClose: 648.54,
  open: 649.20,
  high: 652.10,
  low: 647.90,
  volume: 248600,
  valueKHR: 2315480000,
  marketCapKHR: 15680400000000,
  advancing: 6,
  declining: 3,
  unchanged: 1,
  lastUpdated: new Date().toISOString(),
  isMarketOpen: true,
  tradingSession: 'Continuous Trading (09:00 - 14:50)',
  officialSource: 'Cambodia Securities Exchange (csx.com.kh)',
  tradingMethod: 'Automated Auction Method (AAM) & Negotiated Trading (NTM)',
};

export const INITIAL_NEWS: NewsItem[] = [
  {
    id: 'news-pas-01',
    ticker: 'PAS',
    companyName: 'Sihanoukville Autonomous Port',
    headline: 'PAS New Container Terminal Phase 1 reaches 65% completion milestone',
    khmerHeadline: 'កំពង់ផែស្វយ័តក្រុងព្រះសីហនុ សម្រេចបានការសាងសង់ចំណតផែកុងតឺន័រថ្មីជំហានទី១ ៦៥%',
    source: 'CSX Disclosures & Ministry of Public Works and Transport',
    date: '2026-09-28',
    url: 'https://csx.com.kh/disclosures/pas-phase1-update',
    eventType: 'Infrastructure',
    summary: 'PAS reports that the JICA-financed deep container terminal (Phase 1, 350m berth length, 14.5m draft) has reached 65% construction completion on schedule for mid-2027 commercial operations.',
    aiImpact: {
      event: 'Major Infrastructure Expansion Milestone',
      potentialBusinessEffect: 'Expands container handling capacity from 800k TEUs to 1.25m TEUs; enables direct berthing of 93% of regional feeder vessels without feeder transshipment.',
      potentialFinancialEffect: 'Anticipated long-term container handling revenue increase of 22-28% post-2027; near-term capex supported by 40-year concessional JICA ODA loan.',
      risk: 'Execution and construction timeline delays; global maritime shipping route adjustments.',
      newsImpact: 'Positive',
      impactConfidence: 'High',
      marketPricedIn: 'Partially',
      scoreAdjustment: 4,
      reasoning: 'Project progress reinforces long-term capacity thesis, although near-term stock reaction is tempered because construction has been known to the market.',
    },
  },
  {
    id: 'news-ppap-01',
    ticker: 'PPAP',
    companyName: 'Phnom Penh Autonomous Port',
    headline: 'PPAP reports 14.2% YoY surge in river container throughput for August',
    khmerHeadline: 'កំពង់ផែស្វយ័តភ្នំពេញ រាយការណ៍ពីការកើនឡើងបរិមាណកុងតឺន័រ ១៤.២% ក្នុងខែសីហា',
    source: 'Phnom Penh Post / PPAP Monthly Report',
    date: '2026-09-24',
    url: 'https://csx.com.kh/disclosures/ppap-august-throughput',
    eventType: 'Market Movement',
    summary: 'Phnom Penh Autonomous Port recorded a healthy 14.2% increase in container throughput moving along the Mekong River route to Cai Mep, Vietnam.',
    aiImpact: {
      event: 'Strong Operational Volume Growth',
      potentialBusinessEffect: 'Consolidates PPAP status as key export hub for garments and agro-products along the Mekong River logistics corridor.',
      potentialFinancialEffect: 'Direct positive correlation with Q3 2026 revenue and cash flow.',
      risk: 'Mekong water level seasonality and regional export demand softness.',
      newsImpact: 'Positive',
      impactConfidence: 'Medium',
      marketPricedIn: 'No',
      scoreAdjustment: 3,
      reasoning: 'Operational outperformance provides upside catalyst for dividend sustainability and upcoming Q3 filing.',
    },
  },
  {
    id: 'news-pwsa-01',
    ticker: 'PWSA',
    companyName: 'Phnom Penh Water Supply Authority',
    headline: 'Bakheng Phase 2 Water Treatment facility operates at 92% capacity',
    khmerHeadline: 'រោងចក្រប្រព្រឹត្តកម្មទឹកស្អាតបាក់ខែង ដំណាក់កាលទី២ ដំណើរការបាន ៩២%',
    source: 'Securities and Exchange Regulator of Cambodia (SERC)',
    date: '2026-09-20',
    url: 'https://csx.com.kh/disclosures/pwsa-bakheng-phase2',
    eventType: 'Infrastructure',
    summary: 'PWSA confirmed full commissioning of Bakheng Phase 2, delivering total city production capacity over 1,000,000 m3/day to satisfy expanding peri-urban residential demand.',
    aiImpact: {
      event: 'Capacity Commissioning',
      potentialBusinessEffect: 'Eliminates clean water deficit in southern and western Phnom Penh growth corridors.',
      potentialFinancialEffect: 'Stabilizes baseline utility revenue growth at +8-10% annually with high cash conversion.',
      risk: 'Regulated tariff cap restricts price elasticity.',
      newsImpact: 'Positive',
      impactConfidence: 'High',
      marketPricedIn: 'Yes',
      scoreAdjustment: 2,
      reasoning: 'Steady defensive utility expansion; widely anticipated by institutional holders.',
    },
  },
  {
    id: 'news-abc-01',
    ticker: 'ABC',
    companyName: 'Acleda Bank Plc',
    headline: 'National Bank of Cambodia monetary easing provides liquidity support for commercial banks',
    khmerHeadline: 'ធនាគារជាតិនៃកម្ពុជា បន្ធូរបន្ថយគោលនយោបាយរូបិយវត្ថុ គាំទ្រសន្ទនីយភាពធនាគារ',
    source: 'Khmer Times / NBC Official Bulletin',
    date: '2026-09-18',
    url: 'https://csx.com.kh/news/nbc-monetary-update',
    eventType: 'Regulatory',
    summary: 'The National Bank of Cambodia maintains favorable reserve requirement ratios and KHR liquidity facilities, aiding commercial bank margins and SME restructuring.',
    aiImpact: {
      event: 'Favorable Macro / Regulatory Policy',
      potentialBusinessEffect: 'Reduces funding cost for ABC, enhances net interest margin (NIM) resilience and credit recovery.',
      potentialFinancialEffect: 'Decreases credit provisioning pressure for second half of fiscal year.',
      risk: 'Non-performing loan (NPL) stabilization timeline across real estate and micro-credit portfolios.',
      newsImpact: 'Positive',
      impactConfidence: 'Medium',
      marketPricedIn: 'Partially',
      scoreAdjustment: 3,
      reasoning: 'Supports bank profitability while asset quality normalizes.',
    },
  },
  {
    id: 'news-camgsm-01',
    ticker: 'CAMGSM',
    companyName: 'CamGSM Plc (Cellcard)',
    headline: 'CamGSM reaffirms 7% guaranteed annual dividend commitment in shareholder letter',
    khmerHeadline: 'ក្រុមហ៊ុន CamGSM (Cellcard) បញ្ជាក់ឡើងវិញពីការប្តេជ្ញាចិត្តចែកភាគលាភប្រចាំឆ្នាំ ៧%',
    source: 'CSX Official Disclosure Portal',
    date: '2026-09-15',
    url: 'https://csx.com.kh/disclosures/camgsm-dividend-reaffirmation',
    eventType: 'Dividend',
    summary: 'CamGSM Plc issued an official confirmation of its guaranteed quarterly dividend policy offering an annualized 7% yield for Class A shares for IPO investors.',
    aiImpact: {
      event: 'Dividend Policy Affirmation',
      potentialBusinessEffect: 'Maintains retail investor confidence amidst competitive telecommunications data pricing.',
      potentialFinancialEffect: 'Sustained cash return; high dividend yield creates price floor around 2,300 KHR.',
      risk: 'High capital expenditure required for 5G spectrum rollout and tower maintenance.',
      newsImpact: 'Positive',
      impactConfidence: 'High',
      marketPricedIn: 'Yes',
      scoreAdjustment: 2,
      reasoning: 'Yield attracts income-seeking local investors, capping downside volatility.',
    },
  },
];

export const INITIAL_DISCLOSURES: CSXDisclosure[] = [
  {
    id: 'disc-pas-01',
    ticker: 'PAS',
    title: 'PAS: Unaudited Financial Statements for Q2 2026',
    khmerTitle: 'PAS: របាយការណ៍ហិរញ្ញវត្ថុត្រីមាសទី២ ឆ្នាំ២០២៦',
    date: '2026-08-14',
    category: 'Quarterly Report',
    filingNumber: 'CSX-PAS-2026-042',
    source: 'CSX Disclosures',
    summary: 'PAS generated Q2 gross revenue of 98.4 billion KHR (+11.8% YoY) and net income of 34.2 billion KHR (+15.2% YoY). Container throughput rose 12.1% to 242,100 TEUs.',
    aiTakeaway: 'Robust operational leverage with expanding operating margins; solid support for annual dividend payout.',
    verifiedOfficial: true,
  },
  {
    id: 'disc-pas-02',
    ticker: 'PAS',
    title: 'PAS: Board Resolution Approving 2025 Final Dividend of 520 KHR per Share',
    date: '2026-05-12',
    category: 'Dividend Distribution',
    filingNumber: 'CSX-PAS-2026-025',
    source: 'CSX Disclosures',
    summary: 'The General Meeting of Shareholders approved cash dividend of 520 KHR per share, representing a 4.2% dividend yield at record date price.',
    aiTakeaway: 'Consistent track record of dividend distributions backed by state-enterprise governance.',
    verifiedOfficial: true,
  },
  {
    id: 'disc-ppap-01',
    ticker: 'PPAP',
    title: 'PPAP: Revenue and Operational Report for July 2026',
    date: '2026-08-20',
    category: 'Material Information',
    filingNumber: 'CSX-PPAP-2026-031',
    source: 'CSX Disclosures',
    summary: 'Total revenue reached 3.12 million USD for July 2026 (+8.5% YoY), driven by increased inland barge transfers and storage handling.',
    aiTakeaway: 'Stable throughput growth on the Cambodia-Vietnam logistics water corridor.',
    verifiedOfficial: true,
  },
  {
    id: 'disc-abc-01',
    ticker: 'ABC',
    title: 'ABC: Semi-Annual Financial Report 2026 reviewed by Independent Auditor',
    date: '2026-08-15',
    category: 'Quarterly Report',
    filingNumber: 'CSX-ABC-2026-058',
    source: 'SERC Regulatory Filing',
    summary: 'Total assets reached 41.2 trillion KHR (~10.1 billion USD). Capital adequacy ratio stood at 22.4%, well above NBC statutory minimum.',
    aiTakeaway: 'Strong capital buffer cushions provisioning; balance sheet expansion remains sound.',
    verifiedOfficial: true,
  },
];

export const INITIAL_ALERTS: MarketAlert[] = [
  {
    id: 'alt-01',
    ticker: 'PAS',
    type: 'SCORE_CHANGE',
    severity: 'info',
    title: 'PAS AI Score Updated to 84/100',
    message: 'PAS AI Score increased from 80 → 84 following JICA terminal expansion 65% completion confirmation and Q2 volume acceleration.',
    timestamp: '2026-09-29T08:30:00Z',
    read: false,
  },
  {
    id: 'alt-02',
    ticker: 'PPAP',
    type: 'VOLUME_SURGE',
    severity: 'info',
    title: 'PPAP Above Average Trading Volume',
    message: 'PPAP recorded 32,400 shares traded, 1.8x the 20-day moving average volume.',
    timestamp: '2026-09-28T14:15:00Z',
    read: false,
  },
  {
    id: 'alt-03',
    ticker: 'CSX',
    type: 'PRICE_MOVE',
    severity: 'info',
    title: 'CSX Index Crosses 468 Points',
    message: 'CSX Index rose +0.40% driven by strong bids in port and utility equities.',
    timestamp: '2026-09-30T10:00:00Z',
    read: true,
  },
];

// Helper to build realistic stocks
export function buildCSXStocks(): CSXStock[] {
  const pasHistory = generateHistory(18920, 0.014, 180, 0.0004, 20);
  const pasTech = computeTechnicalIndicators(pasHistory);
  const pasForecast = generate7DayForecast({
    ticker: 'PAS',
    currentPrice: 18920,
    technical: pasTech,
    financials: {
      year: 2025,
      revenueKHR: 382400000000,
      grossProfitKHR: 185600000000,
      operatingIncomeKHR: 132400000000,
      netIncomeKHR: 118200000000,
      totalAssetsKHR: 1680000000000,
      totalLiabilitiesKHR: 720000000000,
      totalEquityKHR: 960000000000,
      cashAndEquivalentsKHR: 145000000000,
      operatingCashFlowKHR: 154000000000,
      capexKHR: 92000000000,
      epsKHR: 1378,
      dpsKHR: 520,
      peRatio: 13.73,
      pbRatio: 1.69,
      roePercent: 12.3,
      debtToEquity: 0.75,
      dividendYieldPercent: 2.75,
    },
    recentNews: INITIAL_NEWS.filter(n => n.ticker === 'PAS'),
    csxIndexTrend: 'Bullish',
  });

  const ppapHistory = generateHistory(15520, 0.012, 180, 0.0002, 20);
  const ppapTech = computeTechnicalIndicators(ppapHistory);
  const ppapForecast = generate7DayForecast({
    ticker: 'PPAP',
    currentPrice: 15520,
    technical: ppapTech,
    recentNews: INITIAL_NEWS.filter(n => n.ticker === 'PPAP'),
  });

  const pwsaHistory = generateHistory(7120, 0.009, 180, 0.0001, 20);
  const pwsaTech = computeTechnicalIndicators(pwsaHistory);
  const pwsaForecast = generate7DayForecast({
    ticker: 'PWSA',
    currentPrice: 7120,
    technical: pwsaTech,
    recentNews: INITIAL_NEWS.filter(n => n.ticker === 'PWSA'),
  });

  const abcHistory = generateHistory(10940, 0.016, 180, -0.0002, 20);
  const abcTech = computeTechnicalIndicators(abcHistory);
  const abcForecast = generate7DayForecast({
    ticker: 'ABC',
    currentPrice: 10940,
    technical: abcTech,
    recentNews: INITIAL_NEWS.filter(n => n.ticker === 'ABC'),
  });

  const camgsmHistory = generateHistory(4020, 0.011, 180, 0.0001, 20);
  const camgsmTech = computeTechnicalIndicators(camgsmHistory);
  const camgsmForecast = generate7DayForecast({
    ticker: 'CAMGSM',
    currentPrice: 4020,
    technical: camgsmTech,
    recentNews: INITIAL_NEWS.filter(n => n.ticker === 'CAMGSM'),
  });

  const gtiHistory = generateHistory(8580, 0.018, 180, -0.0003, 20);
  const gtiTech = computeTechnicalIndicators(gtiHistory);
  const gtiForecast = generate7DayForecast({ ticker: 'GTI', currentPrice: 8580, technical: gtiTech });

  const mjqeHistory = generateHistory(2140, 0.013, 180, 0.0002, 10);
  const mjqeTech = computeTechnicalIndicators(mjqeHistory);
  const mjqeForecast = generate7DayForecast({ ticker: 'MJQE', currentPrice: 2140, technical: mjqeTech });

  const pepcHistory = generateHistory(2410, 0.022, 180, -0.0004, 10);
  const pepcTech = computeTechnicalIndicators(pepcHistory);
  const pepcForecast = generate7DayForecast({ ticker: 'PEPC', currentPrice: 2410, technical: pepcTech });

  const dbdeHistory = generateHistory(2270, 0.015, 180, 0.0001, 10);
  const dbdeTech = computeTechnicalIndicators(dbdeHistory);
  const dbdeForecast = generate7DayForecast({ ticker: 'DBDE', currentPrice: 2270, technical: dbdeTech });

  const jslHistory = generateHistory(2090, 0.025, 180, -0.0005, 10);
  const jslTech = computeTechnicalIndicators(jslHistory);
  const jslForecast = generate7DayForecast({ ticker: 'JSL', currentPrice: 2090, technical: jslTech });

  return [
    {
      ticker: 'PAS',
      name: 'Sihanoukville Autonomous Port',
      khmerName: 'កំពង់ផែស្វយ័តក្រុងព្រះសីហនុ',
      isin: 'KH1000070001',
      sector: 'Transportation & Logistics',
      board: 'Main Board',
      currentPrice: 18920,
      previousClose: 18700,
      change: 220,
      changePercent: 1.18,
      volume: 54600,
      tradingValueKHR: 1033032000,
      marketCapKHR: 1622955916120,
      peRatio: 13.73,
      pbRatio: 1.69,
      epsKHR: 1378,
      dividendYieldPercent: 2.75,
      dpsKHR: 520,
      high52w: 19400,
      low52w: 12800,
      sharesOutstanding: 85779911,
      listingDate: '2017-06-08',
      ceilingPrice: 20570,
      floorPrice: 16830,
      tickSize: 20,
      orderBook: {
        bids: [
          { price: 18920, volume: 2400 },
          { price: 18900, volume: 4600 },
          { price: 18880, volume: 7200 },
        ],
        asks: [
          { price: 18940, volume: 1800 },
          { price: 18960, volume: 3900 },
          { price: 18980, volume: 6500 },
        ],
      },
      foreignOwnership: {
        maxLimitPercent: 49.0,
        currentPercent: 18.4,
        remainingRoomShares: 26252652,
      },
      description: 'PAS operates the sole deep-sea maritime port in the Kingdom of Cambodia, handling approximately 70% of the nation\'s ocean-borne container traffic. It is currently expanding with Japanese ODA assistance to handle mainline mega-containerships.',
      businessHighlights: [
        'Monopoly operator of Cambodia\'s only deep-water commercial seaport',
        'Phase 1 New Container Terminal (14.5m draft) slated for completion mid-2027',
        'Strategic shareholding by Japan International Cooperation Agency (JICA) and JKH',
        'High dividend payout ratio averaging 40-50% of annual net profit',
      ],
      aiScore: {
        overallScore: 84,
        signal: 'Strong Positive',
        fundamentals: {
          score: 23,
          maxScore: 25,
          weightPercent: 25,
          label: 'Fundamentals',
          explanation: 'Exceptional operating moat as Cambodia\'s only deep-sea port. Operating margin of 34.6% and healthy cash flow from operations.',
          keyMetrics: [
            { name: 'Operating Margin', value: '34.6%', assessment: 'positive' },
            { name: 'ROE', value: '12.3%', assessment: 'positive' },
            { name: 'Debt to Equity', value: '0.75x', assessment: 'positive' },
          ],
        },
        growth: {
          score: 17,
          maxScore: 20,
          weightPercent: 20,
          label: 'Growth',
          explanation: 'Container throughput growing at 11-14% CAGR, driven by Cambodian manufacturing exports and Phnom Penh-Sihanoukville expressway connectivity.',
          keyMetrics: [
            { name: 'YoY Container Growth', value: '+12.1%', assessment: 'positive' },
            { name: 'Revenue 3Y CAGR', value: '+10.4%', assessment: 'positive' },
          ],
        },
        valuation: {
          score: 12,
          maxScore: 15,
          weightPercent: 15,
          label: 'Valuation',
          explanation: 'Trading at 9.07x P/E and 1.12x P/B, representing an attractive discount compared to ASEAN port operators (peer average 14-16x P/E).',
          keyMetrics: [
            { name: 'P/E Ratio', value: '9.07x', assessment: 'positive' },
            { name: 'Dividend Yield', value: '4.16%', assessment: 'positive' },
          ],
        },
        technical: {
          score: 8,
          maxScore: 10,
          weightPercent: 10,
          label: 'Technical',
          explanation: 'Price traded above 20-day and 50-day moving averages. RSI at 58.4 indicates bullish momentum with no overbought exhaustion.',
          keyMetrics: [
            { name: 'RSI (14)', value: '58.4', assessment: 'positive' },
            { name: 'SMA Trend', value: 'Price > SMA20 > SMA50', assessment: 'positive' },
          ],
        },
        newsEventImpact: {
          score: 13,
          maxScore: 15,
          weightPercent: 15,
          label: 'News & Disclosures',
          explanation: 'Recent confirmation of 65% Phase 1 terminal completion validates execution timeline and future throughput upside.',
          keyMetrics: [
            { name: 'Latest Event', value: 'JICA Terminal 65% Ready', assessment: 'positive' },
            { name: 'Market Reaction', value: 'Gradual accumulation', assessment: 'positive' },
          ],
        },
        riskScore: {
          score: 7,
          maxScore: 10,
          weightPercent: 10,
          label: 'Risk Profile',
          explanation: 'Low operating risk; moderate exchange rate exposure on JICA yen-denominated debt cushioned by USD billing.',
          keyMetrics: [
            { name: 'Leverage Risk', value: 'Controlled JICA ODA', assessment: 'neutral' },
            { name: 'Geopolitical Risk', value: 'Trade channel dependency', assessment: 'neutral' },
          ],
        },
        liquidity: {
          score: 4,
          maxScore: 5,
          weightPercent: 5,
          label: 'Liquidity',
          explanation: 'Second most liquid stock on CSX with steady institutional and retail daily turnover averaging 45,000+ shares.',
          keyMetrics: [
            { name: 'Daily Turnover', value: '~600M KHR', assessment: 'positive' },
            { name: 'Free Float', value: '25%', assessment: 'neutral' },
          ],
        },
        summaryNarrative: 'PAS continues to be the premier defensive growth proxy for the Cambodian economy. The combination of port monopoly, expanding container capacity, and 4.2% dividend yield supports a Strong Positive analytical stance.',
        lastUpdated: new Date().toISOString(),
      },
      risk: {
        level: 'Medium',
        overallScore: 38,
        factors: [
          { name: 'Maritime Trade Volatility', level: 'Medium', impact: 'Sensitivity to garment export cycles to US/EU', details: 'Container volumes correlate with global consumer demand.' },
          { name: 'Foreign Exchange Debt', level: 'Medium', impact: 'JPY concessional loans require KHR/USD stability', details: 'PAS bills international shipping lines in USD, providing a natural currency hedge.' },
          { name: 'Liquidity Risk', level: 'Low', impact: 'Consistently among top-tier CSX volume leaders', details: 'Exits can be executed within normal trading parameters.' },
          { name: 'Regulatory & State Ownership', level: 'Low', impact: 'Majority owned by Ministry of Economy and Finance', details: 'Strong state backing with strategic Japanese co-investors.' },
        ],
        primaryRisks: ['Global trade slowdown impacting export container throughput', 'Terminal construction cost escalation or supply chain delivery delays'],
        mitigatingFactors: ['Natural currency hedge with USD tariff invoicing', 'Monopoly status on Cambodia deep-sea ocean trade', 'Long-term 40-year concessional financing terms'],
        riskExplanation: 'PAS is rated Medium Risk primarily due to cyclical exposure to global trade demand, offset by an impregnable domestic infrastructure monopoly.',
      },
      forecast7Day: pasForecast,
      technical: pasTech,
      financialHistory: [
        {
          year: 2025,
          revenueKHR: 382400000000,
          grossProfitKHR: 185600000000,
          operatingIncomeKHR: 132400000000,
          netIncomeKHR: 118200000000,
          totalAssetsKHR: 1680000000000,
          totalLiabilitiesKHR: 720000000000,
          totalEquityKHR: 960000000000,
          cashAndEquivalentsKHR: 145000000000,
          operatingCashFlowKHR: 154000000000,
          capexKHR: 92000000000,
          epsKHR: 1378,
          dpsKHR: 520,
          peRatio: 9.07,
          pbRatio: 1.12,
          roePercent: 12.3,
          debtToEquity: 0.75,
          dividendYieldPercent: 4.16,
        },
        {
          year: 2024,
          revenueKHR: 345100000000,
          grossProfitKHR: 164200000000,
          operatingIncomeKHR: 114800000000,
          netIncomeKHR: 102400000000,
          totalAssetsKHR: 1520000000000,
          totalLiabilitiesKHR: 660000000000,
          totalEquityKHR: 860000000000,
          cashAndEquivalentsKHR: 132000000000,
          operatingCashFlowKHR: 138000000000,
          capexKHR: 78000000000,
          epsKHR: 1194,
          dpsKHR: 480,
          peRatio: 10.4,
          pbRatio: 1.25,
          roePercent: 11.9,
          debtToEquity: 0.77,
          dividendYieldPercent: 3.84,
        },
        {
          year: 2023,
          revenueKHR: 312800000000,
          grossProfitKHR: 146900000000,
          operatingIncomeKHR: 98400000000,
          netIncomeKHR: 87100000000,
          totalAssetsKHR: 1390000000000,
          totalLiabilitiesKHR: 590000000000,
          totalEquityKHR: 800000000000,
          cashAndEquivalentsKHR: 118000000000,
          operatingCashFlowKHR: 119000000000,
          capexKHR: 62000000000,
          epsKHR: 1015,
          dpsKHR: 420,
          peRatio: 12.3,
          pbRatio: 1.34,
          roePercent: 10.8,
          debtToEquity: 0.74,
          dividendYieldPercent: 3.36,
        },
      ],
      accuracy: {
        ticker: 'PAS',
        evaluationsCount: 42,
        meanAbsoluteErrorKHR: 165,
        meanAbsolutePercentageError: 1.34,
        directionalAccuracyPercent: 73.8,
        forecastBias: 'Neutral',
        accuracyGrade: 'A',
        recentRecords: [
          {
            id: 'eval-pas-01',
            ticker: 'PAS',
            forecastDate: '2026-09-15',
            targetDate: '2026-09-24',
            forecastPrice: 12420,
            actualPrice: 12480,
            errorKHR: 60,
            errorPercent: 0.48,
            directionPredicted: 'Up',
            directionActual: 'Up',
            directionAccurate: true,
          },
          {
            id: 'eval-pas-02',
            ticker: 'PAS',
            forecastDate: '2026-09-08',
            targetDate: '2026-09-17',
            forecastPrice: 12280,
            actualPrice: 12350,
            errorKHR: 70,
            errorPercent: 0.57,
            directionPredicted: 'Up',
            directionActual: 'Up',
            directionAccurate: true,
          },
          {
            id: 'eval-pas-03',
            ticker: 'PAS',
            forecastDate: '2026-09-01',
            targetDate: '2026-09-10',
            forecastPrice: 12450,
            actualPrice: 12250,
            errorKHR: 200,
            errorPercent: 1.63,
            directionPredicted: 'Up',
            directionActual: 'Down',
            directionAccurate: false,
          },
          {
            id: 'eval-pas-04',
            ticker: 'PAS',
            forecastDate: '2026-08-25',
            targetDate: '2026-09-03',
            forecastPrice: 12200,
            actualPrice: 12220,
            errorKHR: 20,
            errorPercent: 0.16,
            directionPredicted: 'Flat',
            directionActual: 'Flat',
            directionAccurate: true,
          },
        ],
      },
    },
    {
      ticker: 'PPAP',
      name: 'Phnom Penh Autonomous Port',
      khmerName: 'កំពង់ផែស្វយ័តភ្នំពេញ',
      isin: 'KH1000050003',
      sector: 'Transportation & Logistics',
      board: 'Main Board',
      currentPrice: 15520,
      previousClose: 15400,
      change: 120,
      changePercent: 0.78,
      volume: 24800,
      tradingValueKHR: 384896000,
      marketCapKHR: 321021344800,
      peRatio: 8.79,
      pbRatio: 0.99,
      epsKHR: 1764,
      dividendYieldPercent: 4.57,
      dpsKHR: 710,
      high52w: 16200,
      low52w: 13200,
      sharesOutstanding: 20684365,
      listingDate: '2015-12-09',
      ceilingPrice: 16940,
      floorPrice: 13860,
      tickSize: 20,
      orderBook: {
        bids: [
          { price: 15520, volume: 1400 },
          { price: 15500, volume: 3200 },
          { price: 15480, volume: 4600 },
        ],
        asks: [
          { price: 15540, volume: 1100 },
          { price: 15560, volume: 2400 },
          { price: 15580, volume: 3900 },
        ],
      },
      foreignOwnership: {
        maxLimitPercent: 49.0,
        currentPercent: 12.1,
        remainingRoomShares: 7632540,
      },
      description: 'PPAP operates the main river port terminal in Phnom Penh, controlling container freight moving downstream along the Mekong to Vietnam\'s deep-water ports.',
      businessHighlights: [
        'Strategic Mekong river link connecting Phnom Penh to Vietnam Cai Mep',
        'Consistently high dividend payout exceeding 5% annual yield',
        'Expanding sub-terminals and cold chain logistics operations',
      ],
      aiScore: {
        overallScore: 78,
        signal: 'Positive',
        fundamentals: { score: 21, maxScore: 25, weightPercent: 25, label: 'Fundamentals', explanation: 'Strong balance sheet with negligible bank debt and high free cash conversion.', keyMetrics: [{ name: 'Net Margin', value: '38.2%', assessment: 'positive' }] },
        growth: { score: 14, maxScore: 20, weightPercent: 20, label: 'Growth', explanation: 'Steady river container volume (+14.2% YoY).', keyMetrics: [{ name: 'August Volume', value: '+14.2%', assessment: 'positive' }] },
        valuation: { score: 14, maxScore: 15, weightPercent: 15, label: 'Valuation', explanation: 'Trading below book value at 0.88x P/B and under 8x P/E with 5.1% yield.', keyMetrics: [{ name: 'P/B', value: '0.88x', assessment: 'positive' }] },
        technical: { score: 7, maxScore: 10, weightPercent: 10, label: 'Technical', explanation: 'Consolidating in a tight range between 13,600 and 14,100 KHR.', keyMetrics: [{ name: 'RSI', value: '52.1', assessment: 'neutral' }] },
        newsEventImpact: { score: 11, maxScore: 15, weightPercent: 15, label: 'News Impact', explanation: 'August throughput beat expectations.', keyMetrics: [{ name: 'Throughput', value: 'Above trend', assessment: 'positive' }] },
        riskScore: { score: 8, maxScore: 10, weightPercent: 10, label: 'Risk', explanation: 'Low leverage and government backing.', keyMetrics: [{ name: 'Debt Risk', value: 'Minimal', assessment: 'positive' }] },
        liquidity: { score: 3, maxScore: 5, weightPercent: 5, label: 'Liquidity', explanation: 'Moderate trading liquidity.', keyMetrics: [{ name: 'Daily Volume', value: '~18k shares', assessment: 'neutral' }] },
        summaryNarrative: 'PPAP provides deep value with strong dividend yield and river freight tailwinds.',
        lastUpdated: new Date().toISOString(),
      },
      risk: {
        level: 'Low',
        overallScore: 28,
        factors: [
          { name: 'Mekong Hydrology', level: 'Medium', impact: 'Seasonal water levels affect vessel payload draft', details: 'Sub-terminal investments mitigate single-point reliance.' },
          { name: 'Liquidity', level: 'Medium', impact: 'Moderate trading depth on CSX', details: 'Position builds require patient limit orders.' },
        ],
        primaryRisks: ['Cross-border regulatory customs coordination with Vietnam'],
        mitigatingFactors: ['Zero long-term debt', 'Dividend yield above 5%'],
        riskExplanation: 'Priced with substantial margin of safety below book value.',
      },
      forecast7Day: ppapForecast,
      technical: ppapTech,
      financialHistory: [],
      accuracy: {
        ticker: 'PPAP',
        evaluationsCount: 36,
        meanAbsoluteErrorKHR: 142,
        meanAbsolutePercentageError: 1.03,
        directionalAccuracyPercent: 77.8,
        forecastBias: 'Neutral',
        accuracyGrade: 'A',
        recentRecords: [],
      },
    },
    {
      ticker: 'PWSA',
      name: 'Phnom Penh Water Supply Authority',
      khmerName: 'រដ្ឋាករទឹកស្វយ័តក្រុងភ្នំពេញ',
      isin: 'KH1000010004',
      sector: 'Utilities',
      board: 'Main Board',
      currentPrice: 7120,
      previousClose: 7100,
      change: 20,
      changePercent: 0.28,
      volume: 18400,
      tradingValueKHR: 131008000,
      marketCapKHR: 619248913440,
      peRatio: 6.47,
      pbRatio: 0.62,
      epsKHR: 1100,
      dividendYieldPercent: 4.92,
      dpsKHR: 350,
      high52w: 7800,
      low52w: 6860,
      sharesOutstanding: 86973162,
      listingDate: '2012-04-18',
      ceilingPrice: 7810,
      floorPrice: 6390,
      tickSize: 20,
      orderBook: {
        bids: [
          { price: 7120, volume: 3100 },
          { price: 7100, volume: 5400 },
          { price: 7080, volume: 8200 },
        ],
        asks: [
          { price: 7140, volume: 2800 },
          { price: 7160, volume: 4600 },
          { price: 7180, volume: 6900 },
        ],
      },
      foreignOwnership: {
        maxLimitPercent: 49.0,
        currentPercent: 8.5,
        remainingRoomShares: 35224130,
      },
      description: 'The pioneering first listing on CSX, PWSA holds exclusive rights for the treatment and supply of clean potable water to Phnom Penh and surrounding peri-urban zones.',
      businessHighlights: [
        'Exclusive water utility monopoly for capital city',
        'Bakheng Phase 1 & 2 expands clean water capacity past 1M m3/day',
        'Non-revenue water loss among lowest in Asia (<8%)',
      ],
      aiScore: {
        overallScore: 81,
        signal: 'Positive',
        fundamentals: { score: 24, maxScore: 25, weightPercent: 25, label: 'Fundamentals', explanation: 'Monopoly utility cash generator with exceptional collection rate.', keyMetrics: [{ name: 'Operating Margin', value: '41.0%', assessment: 'positive' }] },
        growth: { score: 15, maxScore: 20, weightPercent: 20, label: 'Growth', explanation: 'Steady volume expansion following Bakheng plant scale.', keyMetrics: [{ name: 'Capacity', value: '1M m3/day', assessment: 'positive' }] },
        valuation: { score: 14, maxScore: 15, weightPercent: 15, label: 'Valuation', explanation: 'Undervalued at 6.45x P/E and 0.62x P/B.', keyMetrics: [{ name: 'P/E', value: '6.45x', assessment: 'positive' }] },
        technical: { score: 6, maxScore: 10, weightPercent: 10, label: 'Technical', explanation: 'Low volatility sideways accumulation.', keyMetrics: [{ name: 'ATR', value: '60 KHR', assessment: 'neutral' }] },
        newsEventImpact: { score: 11, maxScore: 15, weightPercent: 15, label: 'News Impact', explanation: 'Bakheng operational status solid.', keyMetrics: [{ name: 'Commissioning', value: 'Complete', assessment: 'positive' }] },
        riskScore: { score: 8, maxScore: 10, weightPercent: 10, label: 'Risk', explanation: 'Safest business model in the market.', keyMetrics: [{ name: 'Tariff Stability', value: 'High', assessment: 'positive' }] },
        liquidity: { score: 3, maxScore: 5, weightPercent: 5, label: 'Liquidity', explanation: 'Defensive hold with modest turnover.', keyMetrics: [{ name: 'Turnover', value: 'Moderate', assessment: 'neutral' }] },
        summaryNarrative: 'PWSA remains the ultimate defensive utility asset in Cambodia.',
        lastUpdated: new Date().toISOString(),
      },
      risk: {
        level: 'Low',
        overallScore: 22,
        factors: [{ name: 'Regulatory Tariff', level: 'Low', impact: 'Tariff changes subject to government review', details: 'Guaranteed cost-plus return structure.' }],
        primaryRisks: ['Electricity input cost changes'],
        mitigatingFactors: ['Essential public utility with 99% collection rate'],
        riskExplanation: 'Extremely resilient defensive profile.',
      },
      forecast7Day: pwsaForecast,
      technical: pwsaTech,
      financialHistory: [],
      accuracy: {
        ticker: 'PWSA',
        evaluationsCount: 40,
        meanAbsoluteErrorKHR: 95,
        meanAbsolutePercentageError: 1.32,
        directionalAccuracyPercent: 72.5,
        forecastBias: 'Neutral',
        accuracyGrade: 'A',
        recentRecords: [],
      },
    },
    {
      ticker: 'ABC',
      name: 'Acleda Bank Plc',
      khmerName: 'ធនាគារ អេស៊ីលីដា ភីអិលស៊ី',
      isin: 'KH1000080000',
      sector: 'Banking & Financials',
      board: 'Main Board',
      currentPrice: 10940,
      previousClose: 10900,
      change: 40,
      changePercent: 0.37,
      volume: 84200,
      tradingValueKHR: 921148000,
      marketCapKHR: 4738802038480,
      peRatio: 10.01,
      pbRatio: 1.15,
      epsKHR: 1092,
      dividendYieldPercent: 3.11,
      dpsKHR: 340,
      high52w: 12200,
      low52w: 9200,
      sharesOutstanding: 433162892,
      listingDate: '2020-05-25',
      ceilingPrice: 11990,
      floorPrice: 9810,
      tickSize: 20,
      orderBook: {
        bids: [
          { price: 10940, volume: 8500 },
          { price: 10920, volume: 14200 },
          { price: 10900, volume: 22100 },
        ],
        asks: [
          { price: 10960, volume: 7200 },
          { price: 10980, volume: 16800 },
          { price: 11000, volume: 28500 },
        ],
      },
      foreignOwnership: {
        maxLimitPercent: 49.0,
        currentPercent: 34.2,
        remainingRoomShares: 64108108,
      },
      description: 'The largest domestic commercial bank in Cambodia by branch network, retail deposits, and balance sheet assets, providing comprehensive consumer, SME, and digital banking.',
      businessHighlights: [
        'Largest commercial bank listed on CSX with >40% of total index weight',
        'Over 3.5 million mobile digital banking users on Acleda Mobile',
        'High tier-1 capital adequacy ratio buffer >22%',
      ],
      aiScore: {
        overallScore: 74,
        signal: 'Neutral',
        fundamentals: { score: 19, maxScore: 25, weightPercent: 25, label: 'Fundamentals', explanation: 'Dominant banking franchise experiencing NPL normalization.', keyMetrics: [{ name: 'NIM', value: '4.8%', assessment: 'positive' }] },
        growth: { score: 13, maxScore: 20, weightPercent: 20, label: 'Growth', explanation: 'Prudent loan growth as bank prioritizes asset quality.', keyMetrics: [{ name: 'Deposit Growth', value: '+7.4%', assessment: 'positive' }] },
        valuation: { score: 13, maxScore: 15, weightPercent: 15, label: 'Valuation', explanation: 'Trades below 1.0x book value.', keyMetrics: [{ name: 'P/B', value: '0.94x', assessment: 'positive' }] },
        technical: { score: 7, maxScore: 10, weightPercent: 10, label: 'Technical', explanation: 'Rebounding from 8,600 support base.', keyMetrics: [{ name: 'RSI', value: '49.8', assessment: 'neutral' }] },
        newsEventImpact: { score: 10, maxScore: 15, weightPercent: 15, label: 'News Impact', explanation: 'NBC liquidity measures supportive.', keyMetrics: [{ name: 'Policy', value: 'Accommodative', assessment: 'positive' }] },
        riskScore: { score: 7, maxScore: 10, weightPercent: 10, label: 'Risk', explanation: 'Credit provisioning remains an active monitoring point.', keyMetrics: [{ name: 'NPL Ratio', value: '4.2%', assessment: 'neutral' }] },
        liquidity: { score: 5, maxScore: 5, weightPercent: 5, label: 'Liquidity', explanation: 'Highest trading liquidity on CSX.', keyMetrics: [{ name: 'Daily Turnover', value: '>600M KHR', assessment: 'positive' }] },
        summaryNarrative: 'ABC provides maximum liquidity and leverage to Cambodia economic turnaround.',
        lastUpdated: new Date().toISOString(),
      },
      risk: {
        level: 'Medium',
        overallScore: 44,
        factors: [{ name: 'Credit Cycle', level: 'Medium', impact: 'Real estate sector loan repayment pace', details: 'Sufficiently covered by loan loss reserves.' }],
        primaryRisks: ['Slower recovery in SME and micro-loan repayments'],
        mitigatingFactors: ['Highest retail deposit base in the country'],
        riskExplanation: 'Balanced risk/reward at sub-1.0x P/B.',
      },
      forecast7Day: abcForecast,
      technical: abcTech,
      financialHistory: [],
      accuracy: {
        ticker: 'ABC',
        evaluationsCount: 45,
        meanAbsoluteErrorKHR: 180,
        meanAbsolutePercentageError: 1.95,
        directionalAccuracyPercent: 68.9,
        forecastBias: 'Neutral',
        accuracyGrade: 'B+',
        recentRecords: [],
      },
    },
    {
      ticker: 'CAMGSM',
      name: 'CamGSM Plc (Cellcard)',
      khmerName: 'ក្រុមហ៊ុន ខេមជីអេសអឹម (សែលខាត)',
      isin: 'KH1000180008',
      sector: 'Telecommunications',
      board: 'Main Board',
      currentPrice: 4020,
      previousClose: 4000,
      change: 20,
      changePercent: 0.50,
      volume: 62400,
      tradingValueKHR: 250848000,
      marketCapKHR: 7879200000000,
      peRatio: 24.9,
      pbRatio: 3.63,
      epsKHR: 161,
      dividendYieldPercent: 4.23,
      dpsKHR: 170,
      high52w: 4400,
      low52w: 2300,
      sharesOutstanding: 1960000000,
      listingDate: '2023-06-27',
      ceilingPrice: 4400,
      floorPrice: 3600,
      tickSize: 20,
      orderBook: {
        bids: [
          { price: 4020, volume: 15400 },
          { price: 4000, volume: 32000 },
          { price: 3980, volume: 45000 },
        ],
        asks: [
          { price: 4040, volume: 12200 },
          { price: 4060, volume: 28500 },
          { price: 4080, volume: 39000 },
        ],
      },
      foreignOwnership: {
        maxLimitPercent: 49.0,
        currentPercent: 6.2,
        remainingRoomShares: 838880000,
      },
      description: 'One of the leading telecommunications network operators in Cambodia, offering voice, 4G LTE data, enterprise cloud solutions, and digital lifestyle services under the Cellcard brand.',
      businessHighlights: [
        'Guaranteed minimum 7% dividend yield commitment for IPO class shareholders',
        'Royal Group flagship telecommunications asset',
        'Expanding fiber enterprise connectivity and FinTech integrations',
      ],
      aiScore: {
        overallScore: 71,
        signal: 'Positive',
        fundamentals: { score: 17, maxScore: 25, weightPercent: 25, label: 'Fundamentals', explanation: 'Strong recurring ARPU cash flows.', keyMetrics: [{ name: 'EBITDA Margin', value: '44.2%', assessment: 'positive' }] },
        growth: { score: 14, maxScore: 20, weightPercent: 20, label: 'Growth', explanation: 'Data consumption growing +18% YoY.', keyMetrics: [{ name: 'Data Usage', value: '+18% YoY', assessment: 'positive' }] },
        valuation: { score: 12, maxScore: 15, weightPercent: 15, label: 'Valuation', explanation: 'Very high dividend yield provides downside protection.', keyMetrics: [{ name: 'Dividend Yield', value: '7.14%', assessment: 'positive' }] },
        technical: { score: 7, maxScore: 10, weightPercent: 10, label: 'Technical', explanation: 'Holding steady in 2,350 - 2,420 channel.', keyMetrics: [{ name: 'Channel', value: 'Stable', assessment: 'neutral' }] },
        newsEventImpact: { score: 10, maxScore: 15, weightPercent: 15, label: 'News Impact', explanation: 'Dividend commitment affirmed.', keyMetrics: [{ name: 'Commitment', value: '7% confirmed', assessment: 'positive' }] },
        riskScore: { score: 7, maxScore: 10, weightPercent: 10, label: 'Risk', explanation: 'High leverage from network capex.', keyMetrics: [{ name: 'Debt', value: 'Elevated capex', assessment: 'neutral' }] },
        liquidity: { score: 4, maxScore: 5, weightPercent: 5, label: 'Liquidity', explanation: 'Active retail following.', keyMetrics: [{ name: 'Volume', value: 'Healthy', assessment: 'positive' }] },
        summaryNarrative: 'CAMGSM is an income stock anchored by high dividend distributions.',
        lastUpdated: new Date().toISOString(),
      },
      risk: {
        level: 'Medium',
        overallScore: 42,
        factors: [{ name: 'Telecom Price Competition', level: 'Medium', impact: 'Mobile data pricing pressure in Cambodia', details: 'Industry consolidating around 3 main players.' }],
        primaryRisks: ['Heavy capex requirements for 5G spectrum'],
        mitigatingFactors: ['7% guaranteed yield floor'],
        riskExplanation: 'Protected by strong dividend guarantee.',
      },
      forecast7Day: camgsmForecast,
      technical: camgsmTech,
      financialHistory: [],
      accuracy: {
        ticker: 'CAMGSM',
        evaluationsCount: 28,
        meanAbsoluteErrorKHR: 32,
        meanAbsolutePercentageError: 1.34,
        directionalAccuracyPercent: 71.4,
        forecastBias: 'Neutral',
        accuracyGrade: 'A',
        recentRecords: [],
      },
    },
    {
      ticker: 'GTI',
      name: 'Grand Twins International (Cambodia) Plc',
      khmerName: 'ហ្រ្គែនធ្វីន អ៊ិនធើណេសិនណល',
      isin: 'KH1000020003',
      sector: 'Consumer Goods & Textiles',
      board: 'Main Board',
      currentPrice: 8580,
      previousClose: 8600,
      change: -20,
      changePercent: -0.23,
      volume: 14800,
      tradingValueKHR: 126984000,
      marketCapKHR: 343200000000,
      peRatio: 34.3,
      pbRatio: 1.38,
      epsKHR: 250,
      dividendYieldPercent: 1.17,
      dpsKHR: 100,
      high52w: 9800,
      low52w: 2600,
      sharesOutstanding: 40000000,
      listingDate: '2014-06-16',
      ceilingPrice: 9460,
      floorPrice: 7740,
      tickSize: 20,
      orderBook: {
        bids: [
          { price: 8580, volume: 800 },
          { price: 8560, volume: 1600 },
          { price: 8540, volume: 2900 },
        ],
        asks: [
          { price: 8600, volume: 700 },
          { price: 8620, volume: 1400 },
          { price: 8640, volume: 2200 },
        ],
      },
      foreignOwnership: {
        maxLimitPercent: 100.0,
        currentPercent: 78.4,
        remainingRoomShares: 8640000,
      },
      description: 'Major athletic apparel and garment manufacturer in Cambodia producing sportswear for global brands including Adidas.',
      businessHighlights: ['Export-oriented garment manufacturer', 'Trades at deep discount to book value (0.45x P/B)'],
      aiScore: {
        overallScore: 62,
        signal: 'Neutral',
        fundamentals: { score: 16, maxScore: 25, weightPercent: 25, label: 'Fundamentals', explanation: 'Cyclical order book.', keyMetrics: [{ name: 'Gross Margin', value: '14.2%', assessment: 'neutral' }] },
        growth: { score: 11, maxScore: 20, weightPercent: 20, label: 'Growth', explanation: 'Moderate garment export growth.', keyMetrics: [{ name: 'Orders', value: 'Stable', assessment: 'neutral' }] },
        valuation: { score: 14, maxScore: 15, weightPercent: 15, label: 'Valuation', explanation: 'Deep discount to book value (0.45x P/B).', keyMetrics: [{ name: 'P/B', value: '0.45x', assessment: 'positive' }] },
        technical: { score: 6, maxScore: 10, weightPercent: 10, label: 'Technical', explanation: 'Low volume sideways trading.', keyMetrics: [{ name: 'Momentum', value: 'Neutral', assessment: 'neutral' }] },
        newsEventImpact: { score: 8, maxScore: 15, weightPercent: 15, label: 'News Impact', explanation: 'Quiet news flow.', keyMetrics: [{ name: 'Filings', value: 'Routine', assessment: 'neutral' }] },
        riskScore: { score: 5, maxScore: 10, weightPercent: 10, label: 'Risk', explanation: 'Global sportswear retail cycles.', keyMetrics: [{ name: 'Client Concentration', value: 'High', assessment: 'negative' }] },
        liquidity: { score: 2, maxScore: 5, weightPercent: 5, label: 'Liquidity', explanation: 'Thin trading volume.', keyMetrics: [{ name: 'Turnover', value: 'Low', assessment: 'negative' }] },
        summaryNarrative: 'Value play with low liquidity, sensitive to Western retail athletic demand.',
        lastUpdated: new Date().toISOString(),
      },
      risk: { level: 'Medium', overallScore: 48, factors: [], primaryRisks: ['Export demand fluctuations'], mitigatingFactors: ['Strong customer relationship with Adidas'], riskExplanation: 'Cyclical order book risk.' },
      forecast7Day: gtiForecast,
      technical: gtiTech,
      financialHistory: [],
      accuracy: { ticker: 'GTI', evaluationsCount: 22, meanAbsoluteErrorKHR: 55, meanAbsolutePercentageError: 1.96, directionalAccuracyPercent: 63.6, forecastBias: 'Neutral', accuracyGrade: 'B', recentRecords: [] },
    },
    {
      ticker: 'MJQE',
      name: 'Mengly J. Quach Education Plc',
      khmerName: 'ក្រុមហ៊ុន ម៉េងលី ជេ. គួច អេឌ្យូខេសិន',
      isin: 'KH1000170009',
      sector: 'Consumer Services & Education',
      board: 'Main Board',
      currentPrice: 2140,
      previousClose: 2120,
      change: 20,
      changePercent: 0.94,
      volume: 38600,
      tradingValueKHR: 82604000,
      marketCapKHR: 706200000000,
      peRatio: 16.7,
      pbRatio: 1.89,
      epsKHR: 128,
      dividendYieldPercent: 4.67,
      dpsKHR: 100,
      high52w: 2400,
      low52w: 2020,
      sharesOutstanding: 330000000,
      listingDate: '2023-06-28',
      ceilingPrice: 2330,
      floorPrice: 1910,
      tickSize: 10,
      orderBook: {
        bids: [
          { price: 2140, volume: 4200 },
          { price: 2130, volume: 8900 },
          { price: 2120, volume: 15400 },
        ],
        asks: [
          { price: 2150, volume: 3800 },
          { price: 2160, volume: 7600 },
          { price: 2170, volume: 12800 },
        ],
      },
      foreignOwnership: {
        maxLimitPercent: 49.0,
        currentPercent: 14.8,
        remainingRoomShares: 112860000,
      },
      description: 'The largest private educational institution listed in Cambodia, operating the Aii Language Center and American Intercon School (AIS) networks nationwide.',
      businessHighlights: ['Market leader in private K-12 and English language training in Cambodia', 'Predictable recurring tuition revenues paid up-front', 'Aggressive campus network expansion into provinces'],
      aiScore: {
        overallScore: 76,
        signal: 'Positive',
        fundamentals: { score: 20, maxScore: 25, weightPercent: 25, label: 'Fundamentals', explanation: 'Negative working capital business model with tuition paid in advance.', keyMetrics: [{ name: 'Cash Conversion', value: 'High', assessment: 'positive' }] },
        growth: { score: 16, maxScore: 20, weightPercent: 20, label: 'Growth', explanation: 'New campus openings driving student enrollment +15% YoY.', keyMetrics: [{ name: 'Student Growth', value: '+15%', assessment: 'positive' }] },
        valuation: { score: 11, maxScore: 15, weightPercent: 15, label: 'Valuation', explanation: 'Premium valuation reflects education moat.', keyMetrics: [{ name: 'P/E', value: '16.7x', assessment: 'neutral' }] },
        technical: { score: 7, maxScore: 10, weightPercent: 10, label: 'Technical', explanation: 'Consolidating above 2,050 support line.', keyMetrics: [{ name: 'Support', value: '2,050 KHR', assessment: 'positive' }] },
        newsEventImpact: { score: 11, maxScore: 15, weightPercent: 15, label: 'News Impact', explanation: 'Provincial campus additions on schedule.', keyMetrics: [{ name: 'Expansion', value: 'On track', assessment: 'positive' }] },
        riskScore: { score: 8, maxScore: 10, weightPercent: 10, label: 'Risk', explanation: 'Essential service highly valued by Cambodian middle class.', keyMetrics: [{ name: 'Resilience', value: 'High', assessment: 'positive' }] },
        liquidity: { score: 3, maxScore: 5, weightPercent: 5, label: 'Liquidity', explanation: 'Moderate retail participation.', keyMetrics: [{ name: 'Liquidity', value: 'Medium', assessment: 'neutral' }] },
        summaryNarrative: 'A high-quality consumer growth proxy backed by demographics and tuition cash generation.',
        lastUpdated: new Date().toISOString(),
      },
      risk: { level: 'Low', overallScore: 30, factors: [], primaryRisks: ['Provincial expansion ramp-up gestation period'], mitigatingFactors: ['Tuition prepaid in cash'], riskExplanation: 'Low business risk model.' },
      forecast7Day: mjqeForecast,
      technical: mjqeTech,
      financialHistory: [],
      accuracy: { ticker: 'MJQE', evaluationsCount: 26, meanAbsoluteErrorKHR: 28, meanAbsolutePercentageError: 1.35, directionalAccuracyPercent: 73.1, forecastBias: 'Neutral', accuracyGrade: 'A', recentRecords: [] },
    },
    {
      ticker: 'PEPC',
      name: 'Pestech (Cambodia) Plc',
      khmerName: 'ប៉េសថិច (ខេមបូឌា)',
      isin: 'KH1000120005',
      sector: 'Energy & Infrastructure',
      board: 'Main Board',
      currentPrice: 2410,
      previousClose: 2420,
      change: -10,
      changePercent: -0.41,
      volume: 12200,
      tradingValueKHR: 29402000,
      marketCapKHR: 180750000000,
      peRatio: 21.3,
      pbRatio: 0.89,
      epsKHR: 113,
      dividendYieldPercent: 2.07,
      dpsKHR: 50,
      high52w: 2800,
      low52w: 2050,
      sharesOutstanding: 75000000,
      listingDate: '2020-08-12',
      ceilingPrice: 2660,
      floorPrice: 2180,
      tickSize: 10,
      orderBook: {
        bids: [
          { price: 2410, volume: 1500 },
          { price: 2400, volume: 3400 },
          { price: 2390, volume: 5100 },
        ],
        asks: [
          { price: 2420, volume: 1800 },
          { price: 2430, volume: 2900 },
          { price: 2440, volume: 4600 },
        ],
      },
      foreignOwnership: {
        maxLimitPercent: 100.0,
        currentPercent: 91.2,
        remainingRoomShares: 6600000,
      },
      description: 'Integrated electric power transmission and distribution substation contractor in Cambodia and Southeast Asia.',
      businessHighlights: ['EPC contractor for high-voltage transmission lines', 'Partner to Electricite du Cambodge (EDC)'],
      aiScore: {
        overallScore: 58,
        signal: 'Negative',
        fundamentals: { score: 14, maxScore: 25, weightPercent: 25, label: 'Fundamentals', explanation: 'Working capital stretched by project milestone receivables.', keyMetrics: [{ name: 'Receivables', value: 'Elevated', assessment: 'negative' }] },
        growth: { score: 11, maxScore: 20, weightPercent: 20, label: 'Growth', explanation: 'Grid infrastructure investment is lumpy.', keyMetrics: [{ name: 'Pipeline', value: 'Moderate', assessment: 'neutral' }] },
        valuation: { score: 11, maxScore: 15, weightPercent: 15, label: 'Valuation', explanation: 'Low P/B reflects project execution uncertainties.', keyMetrics: [{ name: 'P/B', value: '0.78x', assessment: 'positive' }] },
        technical: { score: 5, maxScore: 10, weightPercent: 10, label: 'Technical', explanation: 'Trading below 50-day moving average.', keyMetrics: [{ name: 'Trend', value: 'Bearish', assessment: 'negative' }] },
        newsEventImpact: { score: 8, maxScore: 15, weightPercent: 15, label: 'News Impact', explanation: 'Limited major announcements.', keyMetrics: [{ name: 'News', value: 'Quiet', assessment: 'neutral' }] },
        riskScore: { score: 5, maxScore: 10, weightPercent: 10, label: 'Risk', explanation: 'Counterparty payment cycle risks.', keyMetrics: [{ name: 'Execution Risk', value: 'High', assessment: 'negative' }] },
        liquidity: { score: 4, maxScore: 5, weightPercent: 5, label: 'Liquidity', explanation: 'Moderate turnover.', keyMetrics: [{ name: 'Turnover', value: 'Moderate', assessment: 'neutral' }] },
        summaryNarrative: 'Infrastructure play with higher project execution and working capital risks.',
        lastUpdated: new Date().toISOString(),
      },
      risk: { level: 'High', overallScore: 58, factors: [], primaryRisks: ['Project milestone payment delays'], mitigatingFactors: ['Essential national power grid expansion demand'], riskExplanation: 'High project execution risk.' },
      forecast7Day: pepcForecast,
      technical: pepcTech,
      financialHistory: [],
      accuracy: { ticker: 'PEPC', evaluationsCount: 20, meanAbsoluteErrorKHR: 62, meanAbsolutePercentageError: 2.95, directionalAccuracyPercent: 60.0, forecastBias: 'Slight Upward Bias', accuracyGrade: 'C', recentRecords: [] },
    },
    {
      ticker: 'DBDE',
      name: 'DBD Engineering Plc',
      khmerName: 'ឌីប៊ីឌី អ៊ិនជីនារីង',
      isin: 'KH1000140003',
      sector: 'Industrial & Engineering',
      board: 'Growth Board',
      currentPrice: 2270,
      previousClose: 2260,
      change: 10,
      changePercent: 0.44,
      volume: 8600,
      tradingValueKHR: 19522000,
      marketCapKHR: 43130000000,
      peRatio: 10.4,
      pbRatio: 1.01,
      epsKHR: 218,
      dividendYieldPercent: 5.20,
      dpsKHR: 118,
      high52w: 2490,
      low52w: 2100,
      sharesOutstanding: 19000000,
      listingDate: '2021-09-06',
      ceilingPrice: 2490,
      floorPrice: 2030,
      tickSize: 10,
      orderBook: {
        bids: [
          { price: 2270, volume: 900 },
          { price: 2260, volume: 1800 },
          { price: 2250, volume: 2700 },
        ],
        asks: [
          { price: 2280, volume: 800 },
          { price: 2290, volume: 1500 },
          { price: 2300, volume: 2400 },
        ],
      },
      foreignOwnership: {
        maxLimitPercent: 49.0,
        currentPercent: 5.4,
        remainingRoomShares: 8284000,
      },
      description: 'Mechanical, Electrical, and Plumbing (MEP) engineering contractor listed on the CSX Growth Board.',
      businessHighlights: ['First listing on CSX Growth Board', 'High dividend yield commitment above 5%'],
      aiScore: {
        overallScore: 67,
        signal: 'Neutral',
        fundamentals: { score: 17, maxScore: 25, weightPercent: 25, label: 'Fundamentals', explanation: 'Niche engineering contractor with steady cash payout.', keyMetrics: [{ name: 'Yield', value: '5.20%', assessment: 'positive' }] },
        growth: { score: 12, maxScore: 20, weightPercent: 20, label: 'Growth', explanation: 'Commercial building construction slow recovery.', keyMetrics: [{ name: 'Backlog', value: 'Stable', assessment: 'neutral' }] },
        valuation: { score: 13, maxScore: 15, weightPercent: 15, label: 'Valuation', explanation: 'Low P/E and sub-book valuation.', keyMetrics: [{ name: 'P/E', value: '10.4x', assessment: 'positive' }] },
        technical: { score: 6, maxScore: 10, weightPercent: 10, label: 'Technical', explanation: 'Extremely narrow volatility band.', keyMetrics: [{ name: 'Volatility', value: 'Low', assessment: 'neutral' }] },
        newsEventImpact: { score: 9, maxScore: 15, weightPercent: 15, label: 'News Impact', explanation: 'Consistent dividend distribution compliance.', keyMetrics: [{ name: 'Dividend', value: 'Paid', assessment: 'positive' }] },
        riskScore: { score: 6, maxScore: 10, weightPercent: 10, label: 'Risk', explanation: 'Small market cap Growth Board stock.', keyMetrics: [{ name: 'Market Cap', value: '<50B KHR', assessment: 'negative' }] },
        liquidity: { score: 4, maxScore: 5, weightPercent: 5, label: 'Liquidity', explanation: 'Small daily volume.', keyMetrics: [{ name: 'Liquidity', value: 'Thin', assessment: 'negative' }] },
        summaryNarrative: 'Growth Board MEP contractor paying 5.2% dividend yield with thin liquidity.',
        lastUpdated: new Date().toISOString(),
      },
      risk: { level: 'Medium', overallScore: 46, factors: [], primaryRisks: ['Small cap liquidity risk'], mitigatingFactors: ['Consistent dividend record'], riskExplanation: 'Illiquid Growth Board equity.' },
      forecast7Day: dbdeForecast,
      technical: dbdeTech,
      financialHistory: [],
      accuracy: { ticker: 'DBDE', evaluationsCount: 18, meanAbsoluteErrorKHR: 34, meanAbsolutePercentageError: 1.58, directionalAccuracyPercent: 66.7, forecastBias: 'Neutral', accuracyGrade: 'B', recentRecords: [] },
    },
    {
      ticker: 'JSL',
      name: 'JS Land Plc',
      khmerName: 'ជេអេស លែន',
      isin: 'KH1000150002',
      sector: 'Real Estate',
      board: 'Growth Board',
      currentPrice: 2090,
      previousClose: 2100,
      change: -10,
      changePercent: -0.48,
      volume: 4200,
      tradingValueKHR: 8778000,
      marketCapKHR: 53754800000,
      peRatio: 6.33,
      pbRatio: 0.54,
      epsKHR: 330,
      dividendYieldPercent: 4.78,
      dpsKHR: 100,
      high52w: 4800,
      low52w: 2000,
      sharesOutstanding: 25720000,
      listingDate: '2022-02-10',
      ceilingPrice: 2310,
      floorPrice: 1890,
      tickSize: 10,
      orderBook: {
        bids: [
          { price: 2090, volume: 600 },
          { price: 2080, volume: 1200 },
          { price: 2070, volume: 2100 },
        ],
        asks: [
          { price: 2100, volume: 700 },
          { price: 2110, volume: 1400 },
          { price: 2120, volume: 2500 },
        ],
      },
      foreignOwnership: {
        maxLimitPercent: 49.0,
        currentPercent: 28.5,
        remainingRoomShares: 5272600,
      },
      description: 'Condominium and residential property development company in Phnom Penh (The Garden Residency series).',
      businessHighlights: ['Phnom Penh condominium developer', 'Growth Board listing'],
      aiScore: {
        overallScore: 60,
        signal: 'Neutral',
        fundamentals: { score: 15, maxScore: 25, weightPercent: 25, label: 'Fundamentals', explanation: 'Revenue tied to unit completion handovers.', keyMetrics: [{ name: 'Deliveries', value: 'Cyclical', assessment: 'neutral' }] },
        growth: { score: 12, maxScore: 20, weightPercent: 20, label: 'Growth', explanation: 'Slow recovery in condo pre-sales.', keyMetrics: [{ name: 'Pre-sales', value: 'Moderate', assessment: 'neutral' }] },
        valuation: { score: 12, maxScore: 15, weightPercent: 15, label: 'Valuation', explanation: 'Near 1.0x book value.', keyMetrics: [{ name: 'P/B', value: '1.05x', assessment: 'neutral' }] },
        technical: { score: 5, maxScore: 10, weightPercent: 10, label: 'Technical', explanation: 'Infrequent trading volume.', keyMetrics: [{ name: 'Volume', value: 'Thin', assessment: 'negative' }] },
        newsEventImpact: { score: 8, maxScore: 15, weightPercent: 15, label: 'News Impact', explanation: 'Limited major disclosures.', keyMetrics: [{ name: 'News', value: 'Neutral', assessment: 'neutral' }] },
        riskScore: { score: 5, maxScore: 10, weightPercent: 10, label: 'Risk', explanation: 'Overhang in Phnom Penh high-rise condominium supply.', keyMetrics: [{ name: 'Supply', value: 'Competitive', assessment: 'negative' }] },
        liquidity: { score: 3, maxScore: 5, weightPercent: 5, label: 'Liquidity', explanation: 'Low daily trading turnover.', keyMetrics: [{ name: 'Turnover', value: 'Low', assessment: 'negative' }] },
        summaryNarrative: 'Residential real estate play with slow liquidity.',
        lastUpdated: new Date().toISOString(),
      },
      risk: { level: 'High', overallScore: 55, factors: [], primaryRisks: ['Condominium inventory absorption cycles'], mitigatingFactors: ['Targeted affordable price bracket'], riskExplanation: 'Real estate sector supply sensitivity.' },
      forecast7Day: jslForecast,
      technical: jslTech,
      financialHistory: [],
      accuracy: { ticker: 'JSL', evaluationsCount: 15, meanAbsoluteErrorKHR: 90, meanAbsolutePercentageError: 2.20, directionalAccuracyPercent: 60.0, forecastBias: 'Neutral', accuracyGrade: 'C', recentRecords: [] },
    },
  ];
}
