apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: csx-toysavi-tls
  namespace: csx-analyst
spec:
  secretName: csx-toysavi-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - csx.toysavi.com
