apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: csx-analyst-ingress
  namespace: csx-analyst
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  tls:
    - hosts:
        - csx.toysavi.com
      secretName: csx-toysavi-tls
  rules:
    - host: csx.toysavi.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: csx-analyst-ai
                port:
                  number: 80
